MOUSEKEY_ENABLE = no
RGBLIGHT_ENABLE = no
OLED_ENABLE     = yes
OLED_DRIVER     = SSD1306
LTO_ENABLE      = yes

SWAP_HANDS_ENABLE = yes
AUTO_SHIFT_ENABLE = no
COMBO_ENABLE      = yes
CAPS_WORD_ENABLE  = no
PROGRAMMABLE_BUTTON_ENABLE = no

VPATH += keyboards/gboards

# Squeezing
BOOTMAGIC_ENABLE   = no
NKRO_ENABLE        = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE   = no
MAGIC_ENABLE       = no

CONSOLE_ENABLE = yes
